### ISSUE TITLE
Unable to download pre-trained model due to LFS quota limit

### ISSUE THREAD

**Issue by sngahane** [dennisvdang/chorus-detection#3]
Hey @dennisvdang 👋🏽

First of all, thank you for open sourcing this project, I really appreciate your work in sharing it with the community!

I ran into an issue while trying to clone the repo, specifically when downloading the pre-trained model `best_model_V3.h5`. It seems like the repo has exceeded its data quota for LFS:

```bash
$ git clone https://github.com/dennisvdang/chorus-detection.git
Cloning into 'chorus-detection'...
remote: Enumerating objects: 548, done.
remote: Counting objects: 100% (289/289), done.
remote: Compressing objects: 100% (211/211), done.
remote: Total 548 (delta 112), reused 242 (delta 66), pack-reused 259 (from 1)
Receiving objects: 100% (548/548), 162.22 MiB | 48.15 MiB/s, done.
Resolving deltas: 100% (179/179), done.
Downloading models/CRNN/best_model_V3.h5 (249 MB)
Error downloading object: models/CRNN/best_model_V3.h5 (20e66eb): Smudge error: Error downloading models/CRNN/best_model_V3.h5 (20e66eb3d0788373c3bdc5b28fa2f2587b0e475f3bbc47e8ab9ff0dbdbb2df32): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to '/Users/samueln/workspace/chorus-detection/.git/lfs/logs/20241001T170848.837765.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: models/CRNN/best_model_V3.h5: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
```

I understand the challenges of hosting large files, and I’d be happy to contribute a little bit towards the hosting costs—maybe through a platform like “buy me a coffee” or something similar.

Please let me know if this is something you’d consider, or if there’s another way to access the pre-trained model.

Thanks again for your contribution!

**Comment by dennisvdang** [comment]
Hi @sngahane! Thanks for bringing this to my attention, I wouldn't have known otherwise. Here is a [Google Drive link](https://drive.google.com/file/d/1OoYc5RJwAJo9DmxBHOlP6Qyj1iFvjKoJ/view?usp=sharing) for the model h5 file. Additionally, I've made the file available on HuggingFace at this [repo](https://huggingface.co/dennisvdang/chorus-detection/tree/main). And thank you for the kind offer for contributing to the hosting costs, but hopefully that won't be needed with these other options. Let me know if anything else comes up, and thanks again for reaching out!

**Comment by sngahane** [comment]
Awesome, thanks a ton for this! 👏
